service: ielts-genai-prep
frameworkVersion: '^3.0.0'

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024
  timeout: 30
  
  environment:
    DYNAMODB_USERS_TABLE: ${self:service}-users-${self:provider.stage}
    DYNAMODB_ASSESSMENTS_TABLE: ${self:service}-assessments-${self:provider.stage}
    DYNAMODB_SESSIONS_TABLE: ${self:service}-sessions-${self:provider.stage}
    DYNAMODB_QR_TOKENS_TABLE: ${self:service}-qr-tokens-${self:provider.stage}
    DYNAMODB_ENTITLEMENTS_TABLE: ${self:service}-entitlements-${self:provider.stage}
    DYNAMODB_PURCHASE_RECEIPTS_TABLE: ${self:service}-purchase-receipts-${self:provider.stage}
    APPLE_SHARED_SECRET: ${env:APPLE_SHARED_SECRET}
    GOOGLE_SERVICE_ACCOUNT_JSON: ${env:GOOGLE_SERVICE_ACCOUNT_JSON}
    JWT_SECRET: ${env:JWT_SECRET}
    QR_ENCRYPTION_KEY: ${env:QR_ENCRYPTION_KEY}
    KMS_KEY_ID: ${env:KMS_KEY_ID}
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_USERS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_ASSESSMENTS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_SESSIONS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_QR_TOKENS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_ENTITLEMENTS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_PURCHASE_RECEIPTS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:index/*"
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
            - bedrock:InvokeModelWithResponseStream
          Resource:
            - "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-sonic-v1"
            - "arn:aws:bedrock:*::foundation-model/amazon.nova-micro-v1"
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource:
            - "arn:aws:execute-api:${self:provider.region}:*:*/*/*"
        - Effect: Allow
          Action:
            - kms:GenerateDataKey
            - kms:Decrypt
            - kms:Encrypt
            - kms:DescribeKey
          Resource:
            - "arn:aws:kms:${self:provider.region}:*:key/*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
          Resource:
            - "arn:aws:secretsmanager:${self:provider.region}:*:secret:ielts-genai-prep/*"

functions:
  api:
    handler: handler.lambda_handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
    
  websocket:
    handler: handler.websocket_handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: nova-sonic-stream

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    
    AssessmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_ASSESSMENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: assessment_id
            AttributeType: S
          - AttributeName: user_email
            AttributeType: S
        KeySchema:
          - AttributeName: assessment_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserEmailIndex
            KeySchema:
              - AttributeName: user_email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    
    SessionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_SESSIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: session_id
            AttributeType: S
        KeySchema:
          - AttributeName: session_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expires_at
          Enabled: true
    
    QRTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-qr-tokens-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: token_id
            AttributeType: S
        KeySchema:
          - AttributeName: token_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    
    EntitlementsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-entitlements-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: entitlement_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: entitlement_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserProductIndex
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: product_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    
    PurchaseReceiptsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-purchase-receipts-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: receipt_id
            AttributeType: S
          - AttributeName: transaction_id
            AttributeType: S
        KeySchema:
          - AttributeName: receipt_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: TransactionIndex
            KeySchema:
              - AttributeName: transaction_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true