name: Build Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release)'
        required: true
        default: 'release'
        type: choice
        options:
        - debug
        - release

jobs:
  build-android:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && (github.event.inputs.build_type == 'release' || github.event.inputs.build_type == '') && 'production' || 'development' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
      
    - name: Build web assets
      run: |
        # Ensure web assets directory exists and copy templates (Flask app to Capacitor web)
        mkdir -p static
        cp -r templates/* static/ 2>/dev/null || true
        echo "Web assets prepared for Android:"
        ls -la static/
        
    - name: Sync Capacitor
      run: |
        npx cap sync android
        
    - name: Check Android Signing Prerequisites
      id: check_signing
      run: |
        # Check if all required secrets are present
        if [ -n "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" ]; then
          echo "✓ ANDROID_KEYSTORE_PASSWORD is set"
          echo "has_password=true" >> $GITHUB_OUTPUT
        else
          echo "✗ ANDROID_KEYSTORE_PASSWORD is missing"
          echo "has_password=false" >> $GITHUB_OUTPUT
        fi
        
        echo ""
        echo "⚠️ Note: The following secrets are also required for signed APK builds:"
        echo "  - ANDROID_KEYSTORE_BASE64 (keystore file in base64)"
        echo "  - ANDROID_KEY_ALIAS (key alias name)"
        echo "  - ANDROID_KEY_PASSWORD (key password)"
        echo ""
        echo "Without all secrets, the build will produce an unsigned APK."
        echo "See CREATE_MISSING_SECRETS.md for setup instructions."
    
    - name: Setup Android Release Signing (if secrets available)
      if: (github.event.inputs.build_type == 'release' || github.ref == 'refs/heads/main') && steps.check_signing.outputs.has_password == 'true'
      run: |
        # Only attempt signing if keystore is available
        echo "Checking for keystore secrets..."
        
        # For now, skip signing setup since required secrets are not configured
        echo "⚠️ Signing configuration skipped - missing required secrets"
        echo "The APK will be built unsigned. To enable signing, add:"
        echo "  1. ANDROID_KEYSTORE_BASE64"
        echo "  2. ANDROID_KEY_ALIAS" 
        echo "  3. ANDROID_KEY_PASSWORD"
        echo "to your GitHub repository secrets."
        
    - name: Build Android Debug APK
      if: github.event.inputs.build_type == 'debug' || github.ref != 'refs/heads/main'
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --info --stacktrace
        
    - name: Build Android Release APK
      if: github.event.inputs.build_type == 'release' || github.ref == 'refs/heads/main'
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease --info --stacktrace
        
    - name: Upload Debug APK
      if: github.event.inputs.build_type == 'debug' || github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: ielts-genai-prep-debug-${{ github.run_number }}
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload Release APK
      if: github.event.inputs.build_type == 'release' || github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: ielts-genai-prep-release-${{ github.run_number }}
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 90
        
    - name: Create Release (Requires Manual Approval)
      if: github.ref == 'refs/heads/main' && (github.event.inputs.build_type == 'release' || github.event.inputs.build_type == '')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: IELTS GenAI Prep v${{ github.run_number }}
        body: |
          🚀 **Production Release** - IELTS GenAI Prep Android APK
          
          ⚠️ **This release has been manually approved for distribution**
          
          ## Build Information
          - Commit: ${{ github.sha }}
          - Build: #${{ github.run_number }}
          - Built: ${{ github.run_started_at }}
          
          ## Security Checks
          ✅ SAST scanning passed
          ✅ Dependency vulnerability scanning passed
          ✅ Secret scanning passed
          ✅ APK signed with production keystore
          
          ## Downloads
          - **Android APK**: See release assets below
          
          ## Distribution
          This signed APK is ready for:
          - Google Play Store internal testing track
          - Google Play Store production release
          - Direct distribution (not recommended)
          
        files: android/app/build/outputs/apk/release/app-release.apk
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}